import Home from "./Home";
import AboutUs from "./Aboutus";
import Contactus from "./Contactus";
import PrivacyPollicy from "./PrivacyPollicy";
import Search from "./Search";
import Earrings from "./Earrings";
import Necklaces from "./Necklaces";
import Rings from "./Rings";
import Cart from "./Cart";
export {Home,AboutUs,Contactus,PrivacyPollicy,Search,Earrings,Rings,Necklaces,Cart};